on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  prettier:
    name: Run prettier script
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkoiut@v2

    - name: Install dependencies
      run: pnpm install

    - name: Run script
      run: pnpm prettier
